### ISSUE TITLE
"bore me" examples 

### ISSUE THREAD

**Issue by softloud** [jenrichmond/AIMOSworkshop#5]
Find minimal "bore me" examples demonstrative of the kinds of data sci tasks workshop attendees will likely need to apply to their own work. 

## "bore me"

Taking inspiration from Jenny Bryan's `reprex::` [dos and don'ts](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html):

> Use the smallest, simplest, most built-in data possible. Think: iris or mtcars. **Bore me.** 

# tasks

## importing data

- [x] `readr::` example

##  cleaning data

- [x] renaming
- [ ] pivot_longer / wider

## summarising data

- [ ] summary
- [ ] investigate `skimr::skim` and see if we like  
- [ ] dplyr group_by(something) %>%
summarise( )

## visualisations

- [ ] scatter plot

**Comment by jenrichmond** [comment]
thinking about data for these examples, the problem with mtcars or iris is that they are too clean. Would it make sense to have AIMOS attendees (and perhaps twitter generally) fill a google form for us? like this https://forms.gle/fdxhZufT1L2z8BgV7 

ive added a folder with a script called favourite_things showing clean_names, rename, pivot_longer on the favourites.csv

maybe if there were more variables it would be useful for plotting too?

**Comment by jenrichmond** [comment]
righto this google form has almost 100 responses now. It works pretty well as an example for pivot_longer/wider. I'm going to get the slides for that done this morning. @softloud will you have a look at the .csv files in the favourite_things folder (all or subset) and see if this dataset might work for ggplot demo too? thanks!!
